version: '3.0'
 
services:
  db:
    image: mysql:5.7.25
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: accountowner
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbuserpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  accountownerservice:
    depends_on:
      - db
    image: accountownerservice
    build:
      context: .
    ports:
      - "8080:80"

volumes:
    dbdata: